songs = [

      (r"C:\Users\Senul\Music\BLACKPINK - How You Like That DANCE PERFORMANCE VIDEO.mp3"),
      (r"C:\Users\Senul\Music\Adele - Rolling in the Deep (Official Music Video).mp3" ),
      (r"C:\Users\Senul\Music\[HyunA&amp;DAWN] PING PONG MV.mp3"),
      (r"C:\Users\Senul\Music\TXT TOMORROW X TOGETHER   Anti Romantic.mp3") ,
      (r"C:\Users\Senul\Music\TVXQ - 夜話 (City Lights) (Feat. TAEYONG of NCT) (Sung by Yunho) [129 kbps].mp3") ,
      (r"D:\sogs\You Never Know BlackPink.mp3" ),
      (r"D:\sogs\THE-ALBUM-BLACKPINK-How-You-Like-That-(matikiri.wapkiz.com).mp3" ),
      (r"C:\Users\Senul\Music\taeyang wedding dress.mp3") ,
      (r"C:\Users\Senul\Music\Taeyang - Eyes Nose Lips [128 kbps].mp3") ,
      (r"C:\Users\Senul\Music\mark tuan sanjoy one in a million.mp3"),
      (r"C:\Users\Senul\Music\Maria-hwa-sa-maria-(matikiri.wapkiz.com).mp3") ,
      (r"C:\Users\Senul\Music\MAP OF THE SOUL 7 - BTS - Filter.mp3"),
      (r"C:\Users\Senul\Music\MAP OF THE SOUL 7 - BTS - 0000 (Zero OClock).mp3"),
      (r"C:\Users\Senul\Music\taeyang 링가 링가 ringa linga.mp3") ,
      (r"C:\Users\Senul\Music\TRUE DAMAGE - 'GIANTS' Lyrics _Color Coded_Han_Rom_Eng_ ( 256kbps cbr ).mp3") ,
      (r"C:\Users\Senul\Music\RISE (ft. The Glitch Mob, Mako, and The Word Alive) _ Worlds 2018 - League of Legends ( 256kbps cbr ).mp3") ,
      (r"C:\Users\Senul\Music\Phoenix (ft. Cailin Russo and Chrissy Costanza) _ Worlds 2019 - League of Legends ( 256kbps cbr ).mp3") ,
      (r"C:\Users\Senul\Music\LXX - BLACK _Official MV_ ( 256kbps cbr ).mp3" ),
      (r"C:\Users\Senul\Music\Jin-BTS-Abyss-(matikiri.wapkiz.com).mp3"),
      (r"C:\Users\Senul\Music\Lovesick girls  BlackPink.mp3"),
      (r"C:\Users\Senul\Music\Love To Hate Me  BlackPink.mp3"),
      (r"C:\Users\Senul\Music\Kick It  BlackPink.mp3" ),
      (r"C:\Users\Senul\Music\Jennie (BLACKPINK) - SOLO [320 kbps].mp3" ),
      (r"C:\Users\Senul\Music\ikon 사랑을 했다 love scenario.mp3") ,
      (r"D:\sogs\I' m crasy over you  BlackPink.mp3") ,
      (r"C:\Users\Senul\Music\exo lotto korean ver.mp3"),
      (r"C:\Users\Senul\Music\JOURNEY-HENRY-RADIO-(matikiri.wapkiz.com).mp3"),
      (r"C:\Users\Senul\Music\Jungkook-10000-hours-cover-by-jk-of-bts-(matikiri.wapkiz.com).mp3") ,
      (r"C:\Users\Senul\Music\KEY   Hate that.mp3") ,
      (r"C:\Users\Senul\Music\[MV] NU EST(뉴이스트) _ FACE(페이스).mp3" ),
      (r"C:\Users\Senul\Music\BTS   Spring Day.mp3"),
      (r"D:\sogs\BM - 13IVI [320 kbps].mp3") ,
      (r"C:\Users\Senul\Music\BTS - FAKE LOVE [128 kbps].mp3") ,
      (r"C:\Users\Senul\Music\BTS - Epiphany [321 kbps].mp3") ,
      (r"C:\Users\Senul\Music\BTS - Euphoria [128 kbps].mp3"),
      (r"D:\sogs\blackpink pretty savage.mp3") ,
      (r"D:\sogs\Bet You  Wanna With Kardi BlackPink.mp3") ,
      (r"C:\Users\Senul\Music\exo k baby don t cry 인어의 눈물.mp3"),
      (r"C:\Users\Senul\Music\ddu ddu du BlackPink.mp3"),
      (r"C:\Users\Senul\Music\BTS - I NEED U.mp3"),
      (r"C:\Users\Senul\Music\BTS - The Truth Untold (Feat. Steve Aoki) [128 kbps].mp3"),
      (r"C:\Users\Senul\Music\BTS - Heartbeat-(matikiri.wapkiz.com).mp3") ,
      (r"C:\Users\Senul\Music\David Hasselhoff - True Survivor.mp3"),
      (r"D:\sogs\LOL\KDA-MORE-(matikiri.wapkiz.com).mp3" ),
      (r"D:\sogs\LOL\KDA-VILLAIN-Feat-Madison-Beer-Kim-Petras-(matikiri.wapkiz.com).mp3"),
      (r"D:\sogs\LOL\KDA-ILL-SHOW-YOU-Feat-TWICE-Bekuh-Boom-Annika-Wells-(matikiri.wapkiz.com).mp3"),
      (r"D:\sogs\LOL\KDA-DRUM-GO-DUM-Feat-Wolftyla-Bekuh-Boom-Aluna-(matikiri.wapkiz.com).mp3"),
      (r"D:\sogs\LOL\K_DA - POP_STARS (ft. Madison Beer, (G)I-DLE, Jaira Burns) _ Music Video - League of Legends ( 256kbps cbr ).mp3"),
      (r"C:\Users\Senul\Music\kim chungha 벌써 12시 gotta go.mp3"),
      (r"C:\Users\Senul\Music\BTS - Blood Sweat &amp; Tears [129 kbps] (1).mp3" ),
      (r"C:\Users\Senul\Music\bts mic drop steve aoki remix feat desiigner.mp3" ),
      (r"C:\Users\Senul\Music\Spektrem - Miles Above You.mp3" ),
      (r"C:\Users\Senul\Music\Janji - Heroes Tonight (feat. Johnning) [NCS Release].mp3" ),
      (r"C:\Users\Senul\Music\Unknown Brain - Why Do I ft. Bri Tolani [Clean version].mp3" ),
      (r"C:\Users\Senul\Music\Ed Sheeran - Castle On The Hill [Official].mp3" ),
      (r"C:\Users\Senul\Music\King CAAN ft. ELYSA - Go Again.mp3") ,
      (r"C:\Users\Senul\Music\Arash - Broken Angel (Feat.Helena) (Full English version).mp3"),
      (r"C:\Users\Senul\Music\Wiz Khalifa - See You Again ft. Charlie Puth.mp3"),
      (r"C:\Users\Senul\Music\Cartoon - On &amp; On feat. Daniel Levi.mp3") ,
      (r"C:\Users\Senul\Music\BTS (방탄소년단) Permission to Dance Official MV.mp3"),
      (r"C:\Users\Senul\Music\This Song Will Help You FIND YOUR WAY (Official FIND MY WAY).mp3"),
      (r"D:\sogs\Exra Songs\Smash Mouth - All Star BUGG.mp3" ),
      (r"D:\sogs\Exra Songs\Taio Cruz - Dynamite (Official Music Video).mp3" ),
      (r"D:\sogs\Exra Songs\Alan Walker &amp; K-391 - Ignite ft. Julie Bergan &amp; Seungri.mp3"),
      (r"D:\sogs\Exra Songs\Rain Over Me Pitbull feat Mark Anthony.mp3"),
      (r"D:\sogs\Exra Songs\Arash - Pure Love.mp3") ,
      (r"D:\sogs\Exra Songs\Shawn Mendes, Camila Cabello - Señorita.mp3"),
      (r"D:\sogs\Exra Songs\Ava Max - Sweet but Psycho.mp3") ,
      (r"D:\sogs\Exra Songs\Queen - Another One Bites the Dust (Official Video).mp3"),
      (r"D:\sogs\Exra Songs\Halsey - Without Me.mp3") ,
      (r"C:\Users\Senul\Music\George Michael - Careless Whisper (Official Video).mp3"),
      (r"D:\sogs\Top musics\Vicetone &amp; Tony Igy - Astronomia.mp3"),
      (r"C:\Users\Senul\Music\Tyga - Ayy Macarena.mp3") ,
      (r"C:\Users\Senul\Music\BTS (방탄소년단) - Dynamite.mp3"),
      (r"C:\Users\Senul\Music\All Time Low Monsters ft. blackbear.mp3"),
      (r"D:\sogs\Hindi Songs\11 - Aashiqui (The Love Theme) - DownloadMing.SE.mp3"),
      (r"D:\sogs\Hindi Songs\10 - Milne Hai Mujhse Aayi - DownloadMing.SE.mp3") ,
      (r"D:\sogs\Hindi Songs\09 - Sunn Raha Hai (Female) - DownloadMing.SE.mp3"),
      (r"D:\sogs\Hindi Songs\08 - Aasan Nahin Yahan - DownloadMing.SE.mp3") ,
      (r"D:\sogs\Hindi Songs\07 - Bhula Dena - DownloadMing.SE.mp3" ),
      (r"D:\sogs\Hindi Songs\06 - Piya Aaye Na - DownloadMing.SE.mp3"),
      (r"D:\sogs\Hindi Songs\05 - Meri Aashiqui - DownloadMing.SE.mp3" ),
      (r"D:\sogs\Hindi Songs\04 - Hum Mar Jayenge - DownloadMing.SE.mp3" ),
      (r"D:\sogs\Hindi Songs\03 - Chahun Main Ya Naa - DownloadMing.SE.mp3"),
      (r"D:\sogs\Hindi Songs\02 - Sunn Raha Hai - DownloadMing.SE.mp3"),
      (r"D:\sogs\Hindi Songs\01 - Tum Hi Ho - DownloadMing.SE.mp3"),
      (r"C:\Users\Senul\Music\Bon Jovi - It s my life w .mp3"),
      (r"C:\Users\Senul\Music\Ricky Martin - Livin La Vida Loca.mp3"),
      (r"C:\Users\Senul\Music\Backstreet Boys - Quit Playing Games (With My Heart).mp3"),
      (r"C:\Users\Senul\Music\Backstreet Boys - I Want It That Way (Official Video).mp3") ,
      (r"C:\Users\Senul\Music\Backstreet Boys - Everybody (Backstreet s Back) (Official Video).mp3" ),
      (r"C:\Users\Senul\Music\Stars Align .mp3" ),
      (r"C:\Users\Senul\Music\Drag me Down.mp3"),
      (r"C:\Users\Senul\Music\Without Me - Halsey (Lyrics)_144p.mp3"),
      (r"C:\Users\Senul\Music\We will rock you - Queen-.mp3"),
      (r"C:\Users\Senul\Music\wawin flag.mp3" ),
      (r"C:\Users\Senul\Music\The_Chainsmokers_-_Beach_House.mp3"),
      (r"C:\Users\Senul\Music\sweer but.mp3"),
      (r"C:\Users\Senul\Music\SRT DODGE CAR+MUSIC.mp3" ),
      (r"C:\Users\Senul\Music\Show Me The Meaning .mp3"),
      (r"C:\Users\Senul\Music\senorita.mp3") ,
      (r"C:\Users\Senul\Music\Rowdy Baby-Masstamilan.In.mp3" ),
      (r"C:\Users\Senul\Music\right now-Akon.mp3"),
      (r"C:\Users\Senul\Music\pure love.mp3" ),
      (r"C:\Users\Senul\Music\Pitbull - Rain Over Me ft. Marc Anthony- YouTube.mp3" ),
      (r"C:\Users\Senul\Music\one day im gonna .mp3"),
      (r"C:\Users\Senul\Music\mr. sexobeat.mp3"),
      (r"C:\Users\Senul\Music\Justin_Bieber_-_Boyfriend_(Official_Video)(720p).mp3"),
      (r"C:\Users\Senul\Music\Jax Jones - Breathe (Official Video) ft. Ina Wroldsen_low.mp3" ),
      (r"C:\Users\Senul\Music\Imagine Dragons - Warriors (Lyrics).m4a"),
      (r"C:\Users\Senul\Music\Imagine Dragons - Thunder.m4a") ,
      (r"C:\Users\Senul\Music\Ignite-Alan walker.mp3") ,
      (r"C:\Users\Senul\Music\I-Am-a-Rider-Remix-Bass-Boosted-Ghost-Rider-i-am-a-rider-remix-song_aVbPCtGddsk ,(1).mp3") ,
      (r"C:\Users\Senul\Music\I am on my way.mp3"),
      (r"C:\Users\Senul\Music\Imagine Dragons - Believer_low.mp3" ),
      (r"C:\Users\Senul\Music\I Do Not Own.mp3" ),
      (r"C:\Users\Senul\Music\hit that dram.mp3"),
      (r"C:\Users\Senul\Music\Alan_Walker,_K-391___Emelie_Hollow_-_Lily_(Lyrics).mp3" ),
      (r"C:\Users\Senul\Music\Alan Walker - Alone.m4a"),
      (r"C:\Users\Senul\Music\Get Ready To Fight-(Mr-Jatt.com).mp3" ),
      (r"C:\Users\Senul\Music\Friend-Masmellow MIX.mp3" ),
      (r"C:\Users\Senul\Music\Backstreet Boys - Show Me The Meaning Of Being Lonely (Official Music Video).m4a" ),
      (r"C:\Users\Senul\Music\Alan_Walker_-_Darkside_(feat._Au_Ra_and_Tomine_Harket).mp3" ),
      (r"C:\Users\Senul\Music\Alan_Walker_-_All_Falls_Down_(feat._Noah_Cyrus_with_Digital_Farm_Animals)(256kbps).mp3" ),
      (r"C:\Users\Senul\Music\Clean_Bandit_-_Baby_(feat._Marina_&amp;_Luis_Fonsi)_[Official_Video](720p).mp3"),
      (r"C:\Users\Senul\Music\Clean Bandit - Rockabye (feat. Sean Paul &amp; Anne-Marie) _Official Video_ ( 256kbps cbr ).mp3"),
      (r"C:\Users\Senul\Music\Camila Cabello - Liar (Audio).m4a"),
      (r"C:\Users\Senul\Music\alan-walker-julie-bergan-seungri-Y4MZ59Tj.mp3" ),
      (r"C:\Users\Senul\Music\Alan_Walker_Style_,_Magsonics_&amp;_Broeging_-_Tears_(Music_Video)_ft._Veronica_Bravo(256kbps).mp3"),
      (r"C:\Users\Senul\Music\we don't talk anymore.mp3" ),
      (r"C:\Users\Senul\Music\love shot.mp3") ,
      (r"C:\Users\Senul\Music\Darkside.m4a"),
]
